# Generated by Django 3.1.5 on 2021-01-28 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_leidos',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de autores leídos por el usuario', verbose_name='Autores leídos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, help_text='Breve resumen del Perfil', max_length=500, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha en la que nació', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='libros_leidos',
            field=models.PositiveIntegerField(default=0, help_text='Libros leídos por el usuario', verbose_name='Libros leídos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='Pais donde vive el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.paises', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to='profile_img', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='users',
            field=models.OneToOneField(help_text='Nombre del Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
