version: "3.8"
   
services:
  postgres_myscores:
    container_name: postgres_myscores
    image: postgres:12.7
    hostname: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  django: &django
    build:
      context: .
    container_name: django
    image: my_scores_django
    command: python manage.py runserver 0.0.0.0:8000
    hostname: django
    depends_on:
      - postgres_myscores
    volumes:
      - .:/code
    ports:
      - "8000:8000"

volumes:
  postgresql-data: