# Generated by Django 3.1.5 on 2021-01-31 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del libro leido.', max_length=80, verbose_name='Título')),
                ('autor', models.CharField(help_text='Autor del libro leido.', max_length=80, verbose_name='Autor')),
                ('año_publicacion', models.PositiveIntegerField(blank=True, help_text='Año en que se publico el libro.', max_length=4, null=True, verbose_name='Año de publicación')),
                ('cant_hojas', models.PositiveIntegerField(blank=True, help_text='Cantidad de hojas que tiene el libro.', null=True, verbose_name='Cantidad de Hojas')),
                ('fecha_leido', models.DateField(blank=True, help_text='Fecha en la que se leyó el libro.', null=True, verbose_name='Fecha Leido')),
                ('reseña', models.TextField(blank=True, help_text='Breve reseña del libro leido.', max_length=500, null=True, verbose_name='Reseña')),
                ('user', models.ForeignKey(help_text='Autor que leyó el libro.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
