# Generated by Django 3.2.4 on 2021-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del libro leido.', max_length=80, verbose_name='Título')),
                ('autor', models.CharField(help_text='Autor del libro leido.', max_length=80, verbose_name='Autor')),
                ('año_publicacion', models.PositiveIntegerField(blank=True, help_text='Año en que se publico el libro.', null=True, verbose_name='Año de publicación')),
                ('cant_hojas', models.PositiveIntegerField(blank=True, help_text='Cantidad de hojas que tiene el libro.', null=True, verbose_name='Cantidad de Hojas')),
                ('img_cover', models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to='cover_img', verbose_name='Imagen de Perfil')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
