# Generated by Django 3.1.5 on 2021-02-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del libro leido.', max_length=80, verbose_name='Título')),
                ('autor', models.CharField(help_text='Autor del libro leido.', max_length=80, verbose_name='Autor')),
                ('año_publicacion', models.PositiveIntegerField(blank=True, help_text='Año en que se publico el libro.', null=True, verbose_name='Año de publicación')),
                ('cant_hojas', models.PositiveIntegerField(blank=True, help_text='Cantidad de hojas que tiene el libro.', null=True, verbose_name='Cantidad de Hojas')),
                ('fecha_leido', models.DateField(blank=True, help_text='Fecha en la que se leyó el libro.', null=True, verbose_name='Fecha Leido')),
                ('reseña', models.TextField(blank=True, help_text='Breve reseña del libro leido.', max_length=500, null=True, verbose_name='Reseña')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
